version: '3'
services:
    ethminer-cpp:
        # https://github.com/klutchell/docker-ethminer-cpp
        # https://hub.docker.com/r/klutchell/ethminer-cpp/
        image: "klutchell/ethminer-cpp"
        ports:
            # - "127.0.0.1:8545:8545"
            - "0.0.0.0:30303:30303"
        volumes:
            - /home/ubuntu/.ethereum:/.ethereum
            - /home/ubuntu/.ethash:/.ethash
            - /home/ubuntu/.web3:/.web3
        deploy:
           restart_policy:
             condition: any
             delay: 5s
             max_attempts: 3
             window: 120s
        healthcheck:
            disable: true
        environment:
          - HOME=/
        entrypoint: /usr/local/bin/ethminer -C -F http://ethereumpool.co/?miner=1@0xde3a9EDfe3b285659Ae594F00Bfd2EB783D1443c@dc19-sb32-668149
